### PR TITLE
Store CAA value as raw bytes

### LINKED ISSUE #1353: Resolver claims network is unreachable when iodef URL parsing bails
Observed on released trust-dns-proto/resolver 0.20.0 and 8f1a8eeff8389817d747ee621044f9c73a7f4622

This parsing failure of a probably-invalid iodef eventually causes the resolver to report that the network is unreachable, which seems pretty wrong to me. Ideally I would like to be able to see the bytes that failed to parse as a URL, but the resolver should definitely report the correct problem, and I'd really like to be able to see the rest of the parsed Message, perhaps with the malformed record missing. I'm willing to contribute a patch to fix this if you can offer some guidance.

Offline reproducer:
```rust
use trust_dns_proto::op::message::Message;
fn main() {
    let message: &[u8] = &[
        91, 195, 129, 144, 0, 1, 0, 13, 0, 0, 0, 1, 6, 99, 112, 97, 110, 101, 108, 3, 99, 111, 109,
        0, 0, 255, 0, 1, 192, 12, 0, 1, 0, 1, 0, 0, 0, 99, 0, 4, 208, 74, 121, 151, 192, 12, 0, 1,
        0, 1, 0, 0, 0, 99, 0, 4, 208, 74, 123, 84, 192, 12, 1, 1, 0, 1, 0, 0, 56, 63, 0, 19, 0, 5,
        105, 115, 115, 117, 101, 99, 111, 109, 111, 100, 111, 99, 97, 46, 99, 111, 109, 192, 12, 1,
        1, 0, 1, 0, 0, 56, 63, 0, 35, 0, 5, 105, 111, 100, 101, 102, 109, 97, 105, 108, 116, 111,
        58, 99, 97, 97, 45, 110, 111, 116, 105, 102, 121, 64, 99, 112, 97, 110, 101, 108, 46, 110,
        101, 116, 192, 12, 1, 1, 0, 1, 0, 0, 56, 63, 0, 28, 0, 5, 105, 111, 100, 101, 102, 99, 97,
        97, 45, 110, 111, 116, 105, 102, 121, 64, 99, 112, 97, 110, 101, 108, 46, 110, 101, 116,
        192, 12, 0, 16, 0, 1, 0, 0, 0, 99, 0, 29, 28, 118, 61, 115, 112, 102, 49, 32, 109, 120, 32,
        109, 120, 58, 99, 112, 97, 110, 101, 108, 46, 110, 101, 116, 32, 45, 97, 108, 108, 192, 12,
        0, 16, 0, 1, 0, 0, 0, 99, 0, 130, 129, 104, 111, 117, 45, 49, 46, 102, 114, 111, 110, 116,
        101, 110, 100, 46, 119, 119, 119, 46, 112, 114, 111, 100, 46, 99, 112, 97, 110, 101, 108,
        46, 110, 101, 116, 58, 32, 84, 117, 101, 32, 74, 97, 110, 32, 49, 50, 32, 49, 51, 58, 51,
        49, 58, 49, 49, 32, 50, 48, 50, 49, 32, 72, 84, 84, 80, 32, 79, 75, 58, 32, 72, 84, 84, 80,
        47, 49, 46, 49, 32, 50, 48, 48, 32, 79, 75, 32, 45, 32, 51, 52, 51, 51, 50, 32, 98, 121,
        116, 101, 115, 32, 105, 110, 32, 48, 46, 48, 54, 51, 32, 115, 101, 99, 111, 110, 100, 32,
        114, 101, 115, 112, 111, 110, 115, 101, 32, 116, 105, 109, 101, 192, 12, 0, 16, 0, 1, 0, 0,
        0, 99, 0, 130, 129, 100, 97, 108, 45, 49, 46, 102, 114, 111, 110, 116, 101, 110, 100, 46,
        119, 119, 119, 46, 112, 114, 111, 100, 46, 99, 112, 97, 110, 101, 108, 46, 110, 101, 116,
        58, 32, 84, 117, 101, 32, 74, 97, 110, 32, 49, 50, 32, 49, 51, 58, 51, 50, 58, 51, 57, 32,
        50, 48, 50, 49, 32, 72, 84, 84, 80, 32, 79, 75, 58, 32, 72, 84, 84, 80, 47, 49, 46, 49, 32,
        50, 48, 48, 32, 79, 75, 32, 45, 32, 51, 52, 51, 51, 50, 32, 98, 121, 116, 101, 115, 32,
        105, 110, 32, 48, 46, 48, 49, 49, 32, 115, 101, 99, 111, 110, 100, 32, 114, 101, 115, 112,
        111, 110, 115, 101, 32, 116, 105, 109, 101, 192, 12, 0, 6, 0, 1, 0, 0, 56, 103, 0, 40, 1,
        99, 6, 99, 112, 97, 110, 101, 108, 3, 110, 101, 116, 0, 3, 100, 110, 115, 194, 5, 120, 28,
        79, 3, 0, 0, 56, 64, 0, 0, 28, 32, 0, 36, 234, 0, 0, 1, 81, 128, 192, 12, 0, 2, 0, 1, 0, 0,
        56, 63, 0, 2, 194, 3, 192, 12, 0, 2, 0, 1, 0, 0, 56, 63, 0, 5, 2, 109, 110, 194, 5, 192,
        12, 0, 2, 0, 1, 0, 0, 56, 63, 0, 5, 2, 104, 103, 194, 5, 192, 12, 0, 15, 0, 1, 0, 0, 0,
        139, 0, 8, 0, 0, 3, 109, 120, 49, 192, 12, 0, 0, 41, 2, 0, 0, 0, 128, 0, 0, 0,
    ][..];
    println!("{:?}", Message::from_vec(message));
}
```

Online reproducer:
```rust
use trust_dns_proto::rr::record_type::RecordType;
use trust_dns_resolver::config::{ResolverConfig, ResolverOpts};
use trust_dns_resolver::Resolver;
fn main() {
    let resolver = Resolver::new(ResolverConfig::default(), ResolverOpts::default()).unwrap();
    let response = resolver.lookup("cpanel.net", RecordType::CAA);
    println!("{:?}", response);
}
```

### PR DESCRIPTION
**Pull request by divergentdave**
This changes the CAA struct to store the value as-is, and defer interpreting the value as either a URL or name plus parameters. This closes #1353 and fixes some fuzzer failures.

Note that previously, `emit_value()` and `<Value as Display>::fmt()` encoded empty `issue`/`issuewild` values differently, as either `""` or `";"`. After this PR, there is only one encoding routine, used in the convenience constructors. As a result, some of the expected values in `.to_string()` tests have changed.

### CODE REVIEW

**Review by marcus0x62 — APPROVED** [review]
Looks good!

File: crates/proto/src/rr/rdata/caa.rs [hunk 1]
```diff
@@ -134,15 +134,36 @@ impl CAA {
         self.tag = tag;
     }
 
-    /// a potentially associated value with the property tag, see struct documentation
-    pub fn value(&self) -> &Value {
+    /// A value associated with the property tag, see struct documentation
+    pub fn value(&self) -> &[u8] {
```
Comment (djc) [inline crates/proto/src/rr/rdata/caa.rs:138]: This is a semver-incompatible change. I hoped we would be able to keep main semver-compatible for a while... do you think there's a sensible version of these changes that is semver-compatible?

Comment (divergentdave) [reply crates/proto/src/rr/rdata/caa.rs:138]: Yeah, we'll just have to keep a second copy of the value around in the enum

Comment (djc) [reply crates/proto/src/rr/rdata/caa.rs:138]: Want to try that so we can have a look?

File: crates/proto/src/rr/rdata/caa.rs [hunk 2]
```diff
@@ -134,15 +140,41 @@ impl CAA {
         self.tag = tag;
     }
 
-    /// a potentially associated value with the property tag, see struct documentation
+    /// A value associated with the property tag, see struct documentation
```
Comment (djc) [inline crates/proto/src/rr/rdata/caa.rs:143]: Maybe `#[deprecate]` this, referring to the new methods you've added, and file an issue to follow up on this for the next semver-incompatible release?

File: crates/proto/src/serialize/txt/rdata_parsers/caa.rs [hunk 3]
```diff
@@ -75,27 +75,21 @@ pub(crate) fn parse<'i, I: Iterator<Item = &'i str>>(mut tokens: I) -> ParseResu
...
-            Property::Iodef => {
-                let url = caa::read_iodef(value_str.as_bytes())?;
-                Value::Url(url)
-            }
-            Property::Unknown(_) => Value::Unknown(value_str.as_bytes().to_vec()),
-        }
-    };
+    let raw_value = value_str.as_bytes().to_vec();
+    let mut value_decoder = BinDecoder::new(&raw_value);
+    let value = read_value(
```
Comment (djc) [inline crates/proto/src/serialize/txt/rdata_parsers/caa.rs:80]: Can we do this as a separate commit?

File: crates/proto/src/rr/rdata/caa.rs [hunk 4]
```diff
@@ -807,31 +839,6 @@ impl fmt::Display for Property {
     }
 }
 
-impl fmt::Display for Value {
```
Comment (djc) [inline crates/proto/src/rr/rdata/caa.rs:810]: Can this be a separate commit?

File: crates/proto/src/rr/rdata/caa.rs [hunk 5]
```diff
@@ -134,15 +140,47 @@ impl CAA {
...
+            Value::Unknown(value) => value.clone(),
+        };
         self.value = value;
     }
+
+    /// Get the value of an `issue` or `issuewild` CAA record.
+    ///
+    /// This returns an error if the record's tag is not `issue` or `issuewild`, or if the value
+    /// does not match the expected syntax.
+    pub fn value_as_issue(&self) -> ProtoResult<(Option<Name>, Vec<KeyValue>)> {
```
Comment (djc) [inline crates/proto/src/rr/rdata/caa.rs:163]: So I think the intent here is that we can express these in terms of `raw_value` in the future, right, and this is more like an optimization where we've already parsed a `Value` because of backwards compatibility concerns, right? Perhaps we should add a comment about this? (Same for `value_as_iodef()`?)

**Review by djc — APPROVED** [review]
Nice!

**Comment by divergentdave** [comment]
Yeah, I suppose so. I'll add it back, with another comment.

**Review by djc — APPROVED** [review]
