### PR TITLE
dnssec: report Insecure outcome as NOERROR+AD=0

### LINKED ISSUE #2395: dnssec: hickory responds with SERVFAIL when dealing with Insecure zones
**Describe the bug**
What the title says.

**To Reproduce**
Send the query `A unsigned.extended-dns-errors.com.` to hickory. Hickory responds with SERVFAIL.

**Expected behavior**
The answer should be status=NOERROR with the AD flag *not* set.

**System:**
 - OS: Ubuntu
 - Architecture: x86_64
 - Version 22.04
 - rustc version: 1.80.1

**Version:**
Crate: `hickory-dns`
Version: d80c1720618b309830b3de894f84de97c2672a02

**Additional context**
This should be relatively easy to fix on the server side of things. [This check](https://github.com/hickory-dns/hickory-dns/blob/77bd54e2ca98973b40210f20772d5f7f2de18143/crates/server/src/authority/catalog.rs#L758) needs to consider a third Insecure scenario. However, before doing that more bugs in the DNSSEC validation code need to be ironed out

### PR DESCRIPTION
**Pull request by japaric**
fixes #2395 

but there are still scenarios that hickory mis-clasifies as Bogus when they should be treated as Insecure. Deprecated algorithms, no DS and unsigned zones are among those scenarios. The last two are currently failing due to a NSEC logic bug ( #2435 )

### CODE REVIEW

File: crates/server/src/store/recursor/authority.rs [hunk 1]
```diff
@@ -205,12 +205,15 @@ impl LookupObject for RecursiveLookup {
...
 
-    fn dnssec_validated(&self) -> bool {
-        // TODO research what spec / other impls do when the answer section is empty, DNSSEC
-        // validation is enabled but nameservers provided no NSEC3 records
-        self.0
-            .records()
-            .iter()
-            .all(|record| record.proof().is_secure())
+    fn dnssec_summary(&self) -> DnssecSummary {
+        let proofs = self.0.records().iter().map(|record| record.proof());
```
Comment (djc) [inline crates/server/src/store/recursor/authority.rs:209]: Would suggest formulating as follows:

```rust
let mut secure = true;
for record in self.0.records.iter() {
    match record.proof() {
        Proof::Secure => (),
        Proof::Bogus => return DnsssecSummary::Bogus,
        Proof::Insecure => secure = false,
    }
}

match secure {
    true => DnssecSummary::Secure,
    false => DnssecSummary::Insecure,
}
```

This avoids iterating through records multiple times and IMO makes the logic more clear.

**Review by djc — APPROVED** [review]

File: crates/proto/src/xfer/dnssec_dns_handle.rs [hunk 2]
```diff
@@ -717,15 +717,35 @@ where
                 })
                 .map_ok(|message| {
                     // DNSKEYs were already validated by the inner query in the above lookup
-                    message
+                    let dnskeys = message
```
Comment (djc) [inline crates/proto/src/xfer/dnssec_dns_handle.rs:720]: Nit: let's spell this as `dns_keys`?

File: crates/proto/src/xfer/dnssec_dns_handle.rs [hunk 3]
```diff
@@ -717,15 +717,35 @@ where
...
                         .iter()
-                        .filter_map(|r| r.try_borrow::<DNSKEY>())
-                        // skip DNSKEY that have failed validation
-                        .filter(|r| r.proof().is_secure())
-                        .find_map(|dnskey| {
-                            verify_rrset_with_dnskey(dnskey, *rrsig, &rrset, current_time).ok()
-                        })
+                        .filter_map(|r| r.try_borrow::<DNSKEY>());
+
+                    let mut all_dnskey_are_insecure = true;
```
Comment (djc) [inline crates/proto/src/xfer/dnssec_dns_handle.rs:725]: Nit: just name this `all_insecure`?

File: crates/proto/src/xfer/dnssec_dns_handle.rs (hunk 2 above)
Comment (japaric) [reply crates/proto/src/xfer/dnssec_dns_handle.rs:727]: the `dnskey` identifier is used to refers to `DNSKEY` records and we don't hyphenate them as `dns_key` elsewhere in the codebase so I think this pluralization is more consistent with existing usage of the identifier

**Comment by japaric** [comment]
addressed review comments

File: crates/proto/src/xfer/dnssec_dns_handle.rs (hunk 2 above)
Comment (djc) [reply crates/proto/src/xfer/dnssec_dns_handle.rs:727]: Fair.

**Review by djc — APPROVED** [review]

**Review by bluejekyll — APPROVED** [review]
These look like reasonable changes to me. I don't see anything concerning.
