### PR TITLE
Send error responses in two more cases

### LINKED ISSUE #2572: RFC 8906: Correctly responding to queries in the presence of internal errors
[RFC 8906/BCP 231](https://datatracker.ietf.org/doc/html/rfc8906) discusses the failure of DNS servers to respond to queries, or respond with the correct status code, flags, etc. Not responding to a query requires the client to wait until it times out. Incorrect handling of unrecognized query types, record types, or EDNS options requires clients to implement fallback logic, and impedes protocol evolution.

Section 8 of the document provides an extensive list of tests to perform. I spot checked Hickory DNS against 8.1.4, "Testing Unknown Opcodes", and the request timed out. I have noticed previously that errors decoding messages result in dropping them, which may result in failing other tests. These could be added to the conformance test suite.

### PR DESCRIPTION
**Pull request by divergentdave**
This sends a REFUSED response to clients that are not allowed to make requests, and sends a SERVFAIL response if response encoding otherwise fails for any reason. With these changes, the server will send some reply to requests in almost all cases (except for extreme edge cases like requests that don't even contain a full header). The relevant code path runs through `handle_request()`, `<MessageRequest as BinDecodable>::read()`, `<Catalog as RequestHandler>::handle_request()`, various implementations of `ResponseHandler`, etc. This closes #2572.

### CODE REVIEW

File: crates/server/src/server/mod.rs [hunk 1]
```diff
@@ -1012,6 +1012,25 @@ pub(crate) async fn handle_request<R: ResponseHandler, T: RequestHandler>(
             addr = src_addr.ip(),
             port = src_addr.port(),
         );
+
+        let Ok(header) = Header::read(&mut decoder) else {
+            return;
```
Comment (djc) [inline crates/server/src/server/mod.rs:1017]: So I guess this is a bad case still, right? Add a comment here maybe like `TODO: should send a response` and some context on why that is non-trivial?

File: crates/server/src/server/response_handler.rs [hunk 2]
```diff
@@ -104,9 +109,9 @@ impl ResponseHandler for ResponseHandle {
             impl Iterator<Item = &'a Record> + Send + 'a,
         >,
     ) -> io::Result<ResponseInfo> {
+        let id = response.header().id();
         debug!(
-            "response: {} response_code: {}",
-            response.header().id(),
+            "response: {id} response_code: {}",
```
Comment (djc) [inline crates/server/src/server/response_handler.rs:114]: Nit: convert this to structured logging while you're here?

**Review by djc — APPROVED** [review]
Nice!

File: crates/server/src/server/mod.rs (hunk 1 above)
Comment (divergentdave) [reply crates/server/src/server/mod.rs:1051]: I think this is probably fine, since this now only fails on messages that are less than twelve bytes long. I added a comment to this effect.
