### PR TITLE
Handle shutdown sockets

### LINKED ISSUE #2169: Handle sockets that have been shut down
**Describe the bug**
This error is logged indefinitely after a socket used by a `ServerFuture` has been shut down: `[WARN] error receiving message on udp_socket: Socket is not connected (os error 57)`.

**To Reproduce**
Create a new `ServerFuture` and register a UDP socket using `ServerFuture::register_listener`. Call `pid_shutdown_sockets()` to shut down all sockets owned by the server process.

**Expected behavior**
The server should stop trying to receive data and return an error. Alternatively, the socket should be replaced.

**System:**
 - OS: macOS
 - rustc version: any

**Version:**
Crate: server
Version: 0.23.0

### PR DESCRIPTION
**Pull request by dlon**
Fix #2169. The server stops accepting connections if this fails due to an unrecoverable error. The list of "unrecoverable" errors might not be exhaustive.

### CODE REVIEW

File: crates/server/src/server/server_future.rs [hunk 1]
```diff
@@ -1214,6 +1259,10 @@ fn sanitize_src_address(src: SocketAddr) -> Result<(), String> {
     }
 }
 
+fn is_unrecoverable_socket_error(err: &io::Error) -> bool {
+    matches!(err.raw_os_error(), Some(libc::EBADF | libc::ENOTCONN))
```
Comment (djc) [inline crates/server/src/server/server_future.rs:1263]: It would be nice to avoid pulling in libc for this -- for `ENOTCONN` I think we could use `err.kind()` matching `io::ErrorKind::NotConnected`?

Not sure where you're getting `EBADF` from.

Comment (dlon) [reply crates/server/src/server/server_future.rs:1263]: `EBADF` is what I get from `TcpListener::accept` after calling `pid_shutdown_sockets`. Subsequent calls return `ECONNABORTED` (`ErrorKind::ConnectionAborted`). I suppose we could match `ErrorKind::NotConnected | ErrorKind::ConnectionAborted`?

Comment (djc) [reply crates/server/src/server/server_future.rs:1263]: If that works, sounds good!

Comment (dlon) [reply crates/server/src/server/server_future.rs]: TCP seems a bit hopeless. With `TcpListener` from `std`, `accept` returns immediately when the socket dies, but tokio's equivalent just never returns. I suppose this is still an improvement to prevent the pointless retries.

Comment (djc) [reply crates/server/src/server/server_future.rs]: Might be worth asking some questions in the Tokio issue tracker or on Discord about the behavior there? Sounds suspect.

Comment (dlon) [reply crates/server/src/server/server_future.rs]: I've opened an issue there. How do you think we should handle this in the meantime?

Comment (djc) [reply crates/server/src/server/server_future.rs]: If the Tokio listener just yields pending forever, that seems okay to me for now.

**Review by bluejekyll — APPROVED** [review]
Looks good. Thanks for the PR!

**Comment by faern** [comment]
Would it be possible to have a patch release with this fix in it published? The socket closing cause us significant issues. For now we depend on the git repository, but we want to depend on a crates.io release if possible :pray:

**Comment by djc** [comment]
Sorry for the slow respons -- @bluejekyll seems to be very busy right now -- not sure if he will be able to publish to crates.io (or give me access, maybe via a GitHub team)? If so we can probably make this happen.

**Comment by djc** [comment]
Hey @faern -- sorry for the delay in getting back to you. Apparently we should be able to release from the Actions workflow if I tag a release, so I can (try) to do it after all. Can you try a backport PR? There's no `release/0.24` branch yet so you'll need to start something from the tag (or potentially look through which post-release commits are semver-incompatible).
